# This pipeline depends on a service connection being created in Azure DevOps
trigger:
 branches:
  include:
    - main
 paths:
   exclude:
     - pipelines

name: Deploy Bicep files - $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)-$(Hours)$(Minutes)$(Seconds)

variables:
  vmImageName: 'ubuntu-latest'
  devAzureServiceConnection: 'russ-airs'
  testAzureServiceConnection: 'russ-airs'
  prodAzureServiceConnection: 'russ-airs'
  location: 'uksouth'
  templateFile: '$(Build.SourcesDirectory)/solution/bicep-ado/main.bicep'
  deplymentName: 'ADO-Deploy'
  devParameterFile: '$(Build.SourcesDirectory)/solution/bicep-ado/main.parameters-dev.json'
  testParameterFile: '$(Build.SourcesDirectory)/solution/bicep-ado/main.parameters-test.json'
  prodParameterFile: '$(Build.SourcesDirectory)/solution/bicep-ado/main.parameters-prod.json'


stages:
- stage: 'dev_deploy'
  displayName: 'Deploy to Dev Environment Stage'
  jobs:
  - deployment: 'dev_deploy_bicep'
    displayName: 'Deploy to Dev Environment Deployment'
    pool:
      vmImage: $(vmImageName)
    environment: 
      name: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(devAzureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                ls -R
                az --version
                az deployment sub create -n $(deplymentName) --template-file $(templateFile) --parameters @$(devParameterFile) --location $(location)
- stage: 'test_deploy'
  displayName: 'Deploy to Test Environment Stage'
  jobs:
  - deployment: 'test_deploy_bicep'
    displayName: 'Deploy to Test Environment Deployment'
    pool:
      vmImage: $(vmImageName)
    environment: 
      name: 'test'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(testAzureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az --version
                az deployment sub create -n $(deplymentName) --template-file $(templateFile) --parameters @$(testParameterFile) --location $(location)
- stage: 'prod_deploy'
  displayName: 'Deploy to Prod Environment Stage'
  jobs:
  - deployment: 'prod_deploy_bicep'
    displayName: 'Deploy to Prod Environment Deployment'
    pool:
      vmImage: $(vmImageName)
    environment: 
      name: 'prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(prodAzureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az --version
                az deployment sub create -n $(deplymentName) --template-file $(templateFile) --parameters @$(prodParameterFile) --location $(location)
