trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Copying files to staging directory....
  displayName: 'Copy files to staging directory'
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- script: |
    echo Publishing staging files...
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'