# This pipeline depends on a service connection being created in Azure DevOps
trigger:
 branches:
  include:
    - main
 paths:
   exclude:
     - pipelines

name: Deploy Bicep files - $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)-$(Hours)$(Minutes)$(Seconds)

variables:
  vmImageName: 'ubuntu-latest'
  devAzureServiceConnection: 'Your Azure Connection'
  testAzureServiceConnection: 'Your Azure Connection'
  prodAzureServiceConnection: 'Your Azure Connection'
  location: 'uksouth'
  templateFile: 'main.bicep'
  deplymentName: 'ADO-Deploy'
  devParameterFile: 'main.parameters-dev.json'
  testParameterFile: 'main.parameters-test.json'
  prodParameterFile: 'main.parameters-prod.json'


stages:
- stage: 'dev-deploy'
  displayName: 'Deploy to Dev Environment Stage'
  jobs:
  - job: 'dev-deploy-bicep'
    displayName: 'Deploy to Dev Environment Job'
    pool:
      vmImage: $(vmImageName)
    environment: 'dev'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(devAzureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az deployment sub create -n $(deplymentName) --template-file $(templateFile) --parameters @$(devParameterFile) --location $(location)
- stage: 'test-deploy'
  displayName: 'Deploy to Test Environment Stage'
  jobs:
  - job: 'test-deploy-bicep'
    displayName: 'Deploy to Test Environment Job'
    pool:
      vmImage: $(vmImageName)
    environment: 'test'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(testAzureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az deployment sub create -n $(deplymentName) --template-file $(templateFile) --parameters @$(testParameterFile) --location $(location)
- stage: 'prod-deploy'
  displayName: 'Deploy to Prod Environment Stage'
  jobs:
  - job: 'prod-deploy-bicep'
    displayName: 'Deploy to Prod Environment Job'
    pool:
      vmImage: $(vmImageName)
    environment: 'prod'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(prodAzureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az deployment sub create -n $(deplymentName) --template-file $(templateFile) --parameters @$(prodParameterFile) --location $(location)
